// Mocks generated by Mockito 5.4.6 from annotations
// in stackfood_multivendor_driver/test/cash_in_hand/cash_in_hand_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stackfood_multivendor_driver/feature/cash_in_hand/domain/services/cash_in_hand_service_interface.dart'
    as _i4;
import 'package:stackfood_multivendor_driver/feature/profile/controllers/profile_controller.dart'
    as _i6;
import 'package:stackfood_multivendor_driver/feature/profile/domain/models/profile_model.dart'
    as _i7;
import 'package:stackfood_multivendor_driver/feature/profile/domain/services/profile_service_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProfileServiceInterface_0 extends _i1.SmartFake
    implements _i2.ProfileServiceInterface {
  _FakeProfileServiceInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CashInHandServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockCashInHandServiceInterface extends _i1.Mock
    implements _i4.CashInHandServiceInterface {
  MockCashInHandServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<dynamic> makeCollectCashPayment(
    double? amount,
    String? paymentGatewayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeCollectCashPayment,
          [
            amount,
            paymentGatewayName,
          ],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> makeWalletAdjustment() => (super.noSuchMethod(
        Invocation.method(
          #makeWalletAdjustment,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> getWalletPaymentList() => (super.noSuchMethod(
        Invocation.method(
          #getWalletPaymentList,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}

/// A class which mocks [ProfileController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileController extends _i1.Mock implements _i6.ProfileController {
  MockProfileController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProfileServiceInterface get profileServiceInterface =>
      (super.noSuchMethod(
        Invocation.getter(#profileServiceInterface),
        returnValue: _FakeProfileServiceInterface_0(
          this,
          Invocation.getter(#profileServiceInterface),
        ),
      ) as _i2.ProfileServiceInterface);

  @override
  bool get notification => (super.noSuchMethod(
        Invocation.getter(#notification),
        returnValue: false,
      ) as bool);

  @override
  bool get backgroundNotification => (super.noSuchMethod(
        Invocation.getter(#backgroundNotification),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get shiftLoading => (super.noSuchMethod(
        Invocation.getter(#shiftLoading),
        returnValue: false,
      ) as bool);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_1<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> updateUserInfo(
    _i7.ProfileModel? updateUserModel,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [
            updateUserModel,
            token,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateActiveStatus({
    int? shiftId,
    bool? isUpdate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateActiveStatus,
          [],
          {
            #shiftId: shiftId,
            #isUpdate: isUpdate,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void pickImage() => super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool setNotificationActive(bool? isActive) => (super.noSuchMethod(
        Invocation.method(
          #setNotificationActive,
          [isActive],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setBackgroundNotificationActive(bool? isActive) => super.noSuchMethod(
        Invocation.method(
          #setBackgroundNotificationActive,
          [isActive],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> removeDriver() => (super.noSuchMethod(
        Invocation.method(
          #removeDriver,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> getShiftList() => (super.noSuchMethod(
        Invocation.method(
          #getShiftList,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setShiftId(int? id) => super.noSuchMethod(
        Invocation.method(
          #setShiftId,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void initData() => super.noSuchMethod(
        Invocation.method(
          #initData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startLocationRecord() => super.noSuchMethod(
        Invocation.method(
          #startLocationRecord,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopLocationRecord() => super.noSuchMethod(
        Invocation.method(
          #stopLocationRecord,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> recordLocation() => (super.noSuchMethod(
        Invocation.method(
          #recordLocation,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Disposer addListener(_i8.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i8.Disposer);

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i9.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Disposer addListenerId(
    Object? key,
    _i8.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i8.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
