// Mocks generated by Mockito 5.4.6 from annotations
// in stackfood_multivendor_driver/test/routes/route_optimization_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:image_picker/image_picker.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stackfood_multivendor_driver/api/api_client.dart' as _i8;
import 'package:stackfood_multivendor_driver/common/models/response_model.dart'
    as _i2;
import 'package:stackfood_multivendor_driver/feature/order/domain/models/ignore_model.dart'
    as _i9;
import 'package:stackfood_multivendor_driver/feature/order/domain/models/order_model.dart'
    as _i10;
import 'package:stackfood_multivendor_driver/feature/order/domain/models/update_status_body.dart'
    as _i7;
import 'package:stackfood_multivendor_driver/feature/order/domain/services/order_service_interface.dart'
    as _i6;
import 'package:stackfood_multivendor_driver/feature/routes/domain/models/route_plan_model.dart'
    as _i5;
import 'package:stackfood_multivendor_driver/feature/routes/domain/services/route_service_interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseModel_0 extends _i1.SmartFake implements _i2.ResponseModel {
  _FakeResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RouteServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteServiceInterface extends _i1.Mock
    implements _i3.RouteServiceInterface {
  MockRouteServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.RoutePlanModel?> optimizeRoute(
    String? driverId,
    List<_i5.OptimizeStop>? stops,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizeRoute,
          [
            driverId,
            stops,
          ],
        ),
        returnValue: _i4.Future<_i5.RoutePlanModel?>.value(),
      ) as _i4.Future<_i5.RoutePlanModel?>);

  @override
  _i4.Future<_i5.RoutePlanModel?> getLatestRoute(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestRoute,
          [driverId],
        ),
        returnValue: _i4.Future<_i5.RoutePlanModel?>.value(),
      ) as _i4.Future<_i5.RoutePlanModel?>);
}

/// A class which mocks [OrderServiceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderServiceInterface extends _i1.Mock
    implements _i6.OrderServiceInterface {
  MockOrderServiceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getCompletedOrderList(
    int? offset, {
    required String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedOrderList,
          [offset],
          {#status: status},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getCurrentOrders({required String? status}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentOrders,
          [],
          {#status: status},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getLatestOrders() => (super.noSuchMethod(
        Invocation.method(
          #getLatestOrders,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> updateOrderStatus(
    _i7.UpdateStatusBody? updateStatusBody,
    List<_i8.MultipartBody>? proofAttachment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            updateStatusBody,
            proofAttachment,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getOrderDetails(int? orderID) => (super.noSuchMethod(
        Invocation.method(
          #getOrderDetails,
          [orderID],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> acceptOrder(int? orderID) => (super.noSuchMethod(
        Invocation.method(
          #acceptOrder,
          [orderID],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  void setIgnoreList(List<_i9.IgnoreModel>? ignoreList) => super.noSuchMethod(
        Invocation.method(
          #setIgnoreList,
          [ignoreList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i9.IgnoreModel> getIgnoreList() => (super.noSuchMethod(
        Invocation.method(
          #getIgnoreList,
          [],
        ),
        returnValue: <_i9.IgnoreModel>[],
      ) as List<_i9.IgnoreModel>);

  @override
  _i4.Future<dynamic> getOrderWithId(int? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrderWithId,
          [orderId],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getCancelReasons() => (super.noSuchMethod(
        Invocation.method(
          #getCancelReasons,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  List<_i10.OrderModel> sortDeliveredOrderList(
          List<_i10.OrderModel>? allOrderList) =>
      (super.noSuchMethod(
        Invocation.method(
          #sortDeliveredOrderList,
          [allOrderList],
        ),
        returnValue: <_i10.OrderModel>[],
      ) as List<_i10.OrderModel>);

  @override
  List<_i10.OrderModel> processLatestOrders(
    List<_i10.OrderModel>? latestOrderList,
    List<int?>? ignoredIdList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processLatestOrders,
          [
            latestOrderList,
            ignoredIdList,
          ],
        ),
        returnValue: <_i10.OrderModel>[],
      ) as List<_i10.OrderModel>);

  @override
  List<_i8.MultipartBody> prepareOrderProofImages(
          List<_i11.XFile>? pickedPrescriptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareOrderProofImages,
          [pickedPrescriptions],
        ),
        returnValue: <_i8.MultipartBody>[],
      ) as List<_i8.MultipartBody>);

  @override
  List<int?> prepareIgnoreIdList(List<_i9.IgnoreModel>? ignoredRequests) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareIgnoreIdList,
          [ignoredRequests],
        ),
        returnValue: <int?>[],
      ) as List<int?>);

  @override
  _i4.Future<List<_i10.OrderModel>?> getAvailableOrders(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableOrders,
          [driverId],
        ),
        returnValue: _i4.Future<List<_i10.OrderModel>?>.value(),
      ) as _i4.Future<List<_i10.OrderModel>?>);

  @override
  _i4.Future<List<_i10.OrderModel>?> getActiveOrders(String? driverId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveOrders,
          [driverId],
        ),
        returnValue: _i4.Future<List<_i10.OrderModel>?>.value(),
      ) as _i4.Future<List<_i10.OrderModel>?>);

  @override
  _i4.Future<_i2.ResponseModel> updateOrderStatusNew(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatusNew,
          [
            orderId,
            status,
          ],
        ),
        returnValue: _i4.Future<_i2.ResponseModel>.value(_FakeResponseModel_0(
          this,
          Invocation.method(
            #updateOrderStatusNew,
            [
              orderId,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ResponseModel>);
}
